# Neumím HW dekódovat AV1
ytdl-format=bestvideo[height<=1080][vcodec~='vp9|h265|hevc|h264|avc']+bestaudio/best

#nejaka normalni path pro screenshoty
screenshot-directory=/home/robin/obrazky/screenshoty

# Neukazuje cover-art při přehrávání hudby
audio-display=no

ytdl-raw-options=live-from-start=

hwdec=vaapi
